// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"a1in-bot/app/smsff/internal/conf"
	"a1in-bot/app/smsff/internal/server"
	"a1in-bot/app/smsff/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	smsFFService := service.NewSmsFFService()
	httpServer := server.NewHTTPServer(confServer, smsFFService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
