// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"a1in-bot/app/mikanrss/internal/conf"
	"a1in-bot/app/mikanrss/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	mikanRSSService := service.NewMikanRSSService()
	app := newApp(logger, mikanRSSService)
	return app, func() {
	}, nil
}
